<?php 
$title = 'ほっこりすとになる';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php

$form = $this->form;

$form = $form->setAttribute('action',$this->url(
        'ec',
        array(
            'controller' => 'user',
            'action' => 'add',
        )
        ));

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('name'));
echo $this->formRow($form->get('name'));
echo "<br>";
echo $this->formRow($form->get('email'));
echo "<br>";
echo $this->formRow($form->get('password'));
echo "<br>";
echo $this->formRow($form->get('comment'));
echo "<br>";
echo $this->formRow($form->get('url'));
echo "<br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag($form);

?>

