<?php 
$title = 'ほっこりすとをやめる';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><?php echo $user->name; ?>さんは、ほっこりすとをやめますか？</p>
<?php

$url = $this->url(
        'ec',
        array(
            'controller' => 'user',
            'action' => 'delete',
            'id' => $this->id,
        )
        );
?>

<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $user->id; ?>" />
        <input class="btn btn-success btn-lg" type="submit" name="del" value="はい、やめます" />
        <a class="btn btn-success btn-lg" href ="<?php echo $this->url('ec',
                    array('controller' => 'user',
                        'action' => 'index',
                        )); ?>" >いいえ、やめません</a>
        
    </div>
</form>


