<?php 
$title = 'まいぺーじ';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
<?php if( $isSelf ) : ?>
<tr>
    <th>id</th><td><?php echo $this->escapeHtml($user->id);?></td>
</tr>
<?php endif; ?>
<tr>
    <th>お名前</th><td><?php echo $this->escapeHtml($user->name);?></td>
</tr>
<?php if( $isSelf ) : ?>
<tr>
    <th>メールアドレス</th><td><?php echo $this->escapeHtml($user->email);?></td>
</tr>
<tr>
    <th>パスワード</th><td><?php echo $this->escapeHtml($user->password);?></td>
</tr>
<?php endif; ?>
<tr>
    <th>一言</th><td><?php echo $this->escapeHtml($user->comment);?></td>
</tr>
<tr>
    <th>URL</th><td><?php echo $this->escapeHtml($user->url);?></td>
</tr>
<tr>
    <th>&nbsp;</th><td>
        <a href="<?php echo $this->url('ec',
            array('controller'=>'user',
                'action'=>'index'
                ));?>">ほっこりすと達</a>
<?php if( $isSelf ) : ?>
        <a href="<?php echo $this->url('ec',
            array('controller'=>'user',
                'action'=>'edit',
                'id' => $user->id
                ));?>">編集</a>
        <a href="<?php echo $this->url('ec',
            array('controller'=>'user',
                'action'=>'delete',
                'id' => $user->id
                ));?>">退会</a>
<?php endif; ?>
    </td>
</tr>
</table>
