<?php 
$title = 'ほっこりすとの編集';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php

$form = $this->form;

$form = $form->setAttribute('action',$this->url(
        'ec',
        array(
            'controller' => 'user',
            'action' => 'edit',
            'id' => $this->id,
        )
        ));

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('comment'));
echo $this->formRow($form->get('url'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag($form);

?>
