<?php 
$title = 'ほっこりすとのみんな';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<!--変更メッセージ-->
<?php if( strlen( $message ) ) : ?>
<div style='padding:4px; margin:4px; border:dotted 2px #448800; background:#ddffdd;'>
    <?php  echo $message; ?>
</div>
<?php endif; ?>

<!--コメント投稿一覧-->
<p>
    <a class="btn btn-success btn-lg" href ="<?php echo $this->url('ec',
                    array('controller' => 'comment',
                        'action' => 'index',
                    )); ?>"><?php echo $this->translate('ほっこりすと') ?></a>
</p>

<!--ログインユーザー名の表示-->
<?php
    if( $login_user->id ){
        echo $this->escapeHtml($login_user->name) . 'さん はログインしてますよ';
    }
?>

<!--ユーザ一覧-->
<table class="table">
    <tr>
        <th>ほっこりすとNo</th>
        <th>お名前</th>
        <th>&nbsp;</th>
    </tr>
<?php     foreach ( $users as $user) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($user->id); ?></td>
        <td><?php echo $this->escapeHtml($user->name); ?></td>
        <td>
        <a href ="<?php echo $this->url('ec',
                    array('controller' => 'user',
                        'action' => 'detail',
                        'id' => $user->id
                    )); ?>">プロフィール</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>

<!--ユーザ新規登録-->
<p>
    <a class="btn btn-success btn-lg" href="<?php echo $this->url('ec',
                    array('controller' => 'user',
                        'action' => 'add',
                    )); ?>"><?php echo $this->translate('ほっこりすとになる') ?></a>
</p>

<!--ログアウト-->
<p>
    <a href ="<?php echo $this->url('ec',
                    array('controller' => 'index',
                        'action' => 'logout',
                    )); ?>"><?php echo $this->translate('ログアウト') ?></a>
</p>
