<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ほっこりすと') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/dengen.png'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/dengen.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('ほっこりすと') ?></a>
                </div>
                <!--start ヘッダーバー -->
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('トップ') ?></a>ホーム</li>
                            <li class="active"><a href="<?php echo $this->url('ec', array('controller'=>'comment','action'=>'index'));?>">ほっこりすと</a></li>
                            <li class="active"><a href="<?php echo $this->url('ec', array('controller'=>'user','action'=>'index'));?>">ほっこりすとのみんな</a></li>
                            <li class="active"><a href="<?php echo $this->url('ec', array('controller'=>'user','action'=>'add'));?>">ほっこりすとになる</a></li>                            
                            <li class="active"><a href="<?php echo $this->url('ec', array('controller'=>'user','action'=>'mypage'));?>">まいぺーじ</a></li>
                            <li class="active"><a href="<?php echo $this->url('ec', array('controller'=>'index','action'=>'login'));?>">ログイン</a></li>
                            <li class="active"><a href="<?php echo $this->url('ec', array('controller'=>'index','action'=>'logout'));?>">ログアウト</a></li>
                     
                    </ul>
                </div><!--/.nav-collapse -->
                <!--end ヘッダーバー-->
            </div>
        </nav>
        <div class="container">
            <!--アクションごとのviewを展開-->
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by onoe adusa <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
