<a></a>
<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('ほっこりすと'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('<br>ほっこりする、されるSNS <br><br>まずは「ほっこりすと」になって
ほっこりエピソードを投稿してみよう'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <p><a class="btn btn-success btn-lg" href="<?php echo $this->url('ec',
                    array('controller' => 'user',
                        'action' => 'add',
                    )); ?>"><?php echo $this->translate('ほっこりすとになる') ?></a>
    </p>

    <p><a class="btn btn-success btn-lg" href="<?php echo $this->url('ec',
                    array('controller' => 'comment',
                        'action' => 'index',
                    )); ?>"><?php echo $this->translate('ほっこりを見る') ?></a>
    </p>

    <p><a class="btn btn-success btn-lg" href="<?php echo $this->url('ec',
                    array('controller' => 'user',
                        'action' => 'index',
                    )); ?>"><?php echo $this->translate('ほっこりすとのみんな') ?></a>
    </p>     
    
    
</div>
