<?php 
$title = 'ログイン';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php if( strlen( $message ) ) : ?>
<div style='padding:4px; margin:4px; border:dotted 2px #448800; background:#ddffdd;'>
    <?php  echo $message; ?>
</div>
<?php endif; ?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'ec',
    array(
        'controller' => 'index',
        'action'     => 'login',
    )
));

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('email'));
echo "<br>";
echo $this->formRow($form->get('password'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>

