<?php 
$title = 'ほっこりを投稿する';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'ec',
    array(
        'controller' => 'comment',
        'action'     => 'add',
    )
));

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo "<br>";
echo $this->formRow($form->get('comment'));
echo $this->formHidden($form->get('parent_id'));
echo $this->formHidden($form->get('user_id'));
echo "<br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>

</br>
<!-- コメント投稿一覧画面 -->
<a href="<?php echo $this->url('ec',
            array('controller'=>'comment',
                'action'=>'index'
                ));?>">ほっこりすと</a>
<br>
<!-- ユーザー一覧画面 -->
<a href="<?php echo $this->url('ec',
            array('controller'=>'user',
                'action'=>'index'
                ));?>">ほっこりすとのみんな</a>