<?php 
$title = 'ほっこりすとの会話';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php if( strlen( $message ) ) : ?>
<div style='padding:4px; margin:4px; border:dotted 2px #448800; background:#ddffdd;'>
    <?php  echo $message; ?>
</div>
<?php endif; ?>
<table class="table">
<tr>
    <td style='font-weight:bold;'><?php echo $this->escapeHtml($comment->title);?></td>
</tr>
<tr>
    <td>
        <?php echo nl2br( $this->escapeHtml( $comment->comment ) );?>
        <p style='text-align:right; font-weight:bold;'>

            <a href='<?php echo $this->url('ec',
            array('controller'=>'user',
                'action'=>'detail',
                'id' => $comment_user->id
                    ));?>'>
                <?php echo $this->escapeHtml($comment_user->name);?>
            </a>
        </p>
    </td>
</tr>
</table>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'ec',
    array(
        'controller' => 'comment',
        'action'     => 'detail',
        'id'         => $comment->id,
    )
));

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('comment'));
echo $this->formHidden($form->get('parent_id'));
echo $this->formHidden($form->get('user_id'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>

<table class="table">
<tr>
    <th>コメント</th>
</tr>
<?php foreach ($comment_res as $res) : ?>
<tr>
    <td>
        <?php echo nl2br( $this->escapeHtml( $res['comment'] ) );?>
        <p style="text-align:right; font-weight:bold;">

            <a href="<?php echo $this->url('ec',
            array('controller'=>'user',
                'action'=>'detail',
                'id' => $res['user_id']
                    ));?>">
                <?php echo $this->escapeHtml($res['user_name']);?>
            </a>
        </p>
    </td>
</tr>
<?php endforeach; ?>
</table>

<!--コメント一覧画面->
<a href="<?php echo $this->url('ec',
            array('controller'=>'comment',
                'action'=>'index'
                ));?>">ほっこりすと</a>



