<?php 
$title = 'COMMENT DETAIL';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php if( strlen( $message ) ) : ?>
<div style='padding:4px; margin:4px; border:dotted 2px #448800; background:#ddffdd;'>
    <?php  echo $message; ?>
</div>
<?php endif; ?>
<table class="table">
<tr>
    <td style='font-weight:bold;'><?php echo $this->escapeHtml($comment->title);?></td>
</tr>
<tr>
    <td>
        <?php echo nl2br( $this->escapeHtml( $comment->comment ) );?>
        <p style='text-align:right; font-weight:bold;'>
            ≈Íπ∆º‘°ß
            <a href='<?php echo $this->url('ec',
            array('controller'=>'user',
                'action'=>'detail',
                'id' => $comment_user->id
                    ));?>'>
                <?php echo $this->escapeHtml($comment_user->name);?>
            </a>
        </p>
    </td>
</tr>
</table>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'ec',
    array(
        'controller' => 'comment',
        'action'     => 'detail',
        'id'         => $comment->id,
    )
));

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('comment'));
echo $this->formHidden($form->get('parent_id'));
echo $this->formHidden($form->get('user_id'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>

<table class="table">
<tr>
    <th>LESS ALL</th>
</tr>
<?php foreach ($comment_res as $res) : ?>
<tr>
    <td>
        <?php echo nl2br( $this->escapeHtml( $res['comment'] ) );?>
        <p style="text-align:right; font-weight:bold;">
            ≈Íπ∆º‘°ß
            <a href="<?php echo $this->url('ec',
            array('controller'=>'user',
                'action'=>'detail',
                'id' => $res['user_id']
                    ));?>">
                <?php echo $this->escapeHtml($res['user_name']);?>
            </a>
        </p>
    </td>
</tr>
<?php endforeach; ?>
</table>






<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sZend Framework 2%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zf2" target="_blank"><?php echo $this->translate('Fork Zend Framework 2 on GitHub') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('ZF2 Development Portal') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Discover Modules') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Explore ZF2 Modules') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Help &amp; Support') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
