<?php 
$title = 'ほっこりすと';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php if( strlen( $message ) ) : ?>
<div style='padding:4px; margin:4px; border:dotted 2px #448800; background:#ddffdd;'>
    <?php  echo $message; ?>
</div>
<?php endif; ?>
<p>
    <a class="btn btn-success btn-lg" href="<?php echo $this->url('ec',
         array('controller'=>'comment',
             'action'=>'add'
             ));?>">「ほっこり」を共有しよう</a>
</p>
<table class="table">

<?php foreach ($comments as $comment) : ?>
<tr>
    <td>
        <a href="<?php echo $this->url('ec',
            array('controller'=>'comment',
                'action'=>'detail',
                'id' => $comment['id']
                ));?>"><?php echo $this->escapeHtml($comment['title']);?></a>
        <p style='text-align:right; font-weight:bold;'>
            
            <a href="<?php echo $this->url('ec',
            array('controller'=>'user',
                'action'=>'detail',
                'id' => $comment['user_id']
                 ));?>">
                <?php echo $this->escapeHtml($comment['user_name']);?>
            </a>
        </p>
    </td>
</tr>
<?php endforeach; ?>
</table>

</br>
<!--ユーザー一覧画面-->
<a class="btn btn-success btn-lg" href="<?php echo $this->url('ec',
            array('controller'=>'user',
                'action'=>'index'
                ));?>">ほっこりすとのみんな</a>
